<?xml version="1.0" encoding="utf-8"?><Database Name="Garcia" Class="GarciaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=Garcia;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GarciaConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HOBO" Member="HOBOs">
    <Type Name="HOBO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HOBO_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[_DateTime]" Member="_DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Temp" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DewPoint" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AbsHumidity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DateUploaded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UploadedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.lut_SITE_INFO" Member="SITE_INFOs">
    <Type Name="SITE_INFO">
      <Column Name="OBJECTID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Site_ID" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="SITE_NAME" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Directions" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.lut_SITE_x_HOBO" Member="SiteXHoboRows">
    <Type Name="SiteXHoboRow">
      <Column Name="OBJECTID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SITE_ID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HOBO_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YEAR_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CONTRIBUTOR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="COMMENTS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sdeloader.SITE" Member="SITEs">
    <Type Name="SITE">
      <Column Name="OBJECTID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Site_ID" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Shape" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.lut_SITE_x_HOBO" Member="SiteHobos">
    <Type Name="SiteHobo">
      <Column Name="OBJECTID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SITE_ID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HOBO_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YEAR_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CONTRIBUTOR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="COMMENTS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FinalMWAT" Member="FinalMWATs">
    <Type Name="FinalMWAT">
      <Column Name="SITE_NAME" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="HOBO_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tavg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="movAvg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hoboday" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="threshold" Type="System.Decimal" DbType="Decimal(28,1)" CanBeNull="true" />
      <Column Name="YEAR_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaxOfmovAvg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SiteID" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FinalMWMT" Member="FinalMWMTs">
    <Type Name="FinalMWMT">
      <Column Name="SiteID" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="SITE_NAME" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="HOBO_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tmax" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="movAvg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hoboday" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="threshold" Type="System.Decimal" DbType="Decimal(28,1)" CanBeNull="true" />
      <Column Name="YEAR_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaxOfmovAvg" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MWAT" Member="MWATs">
    <Type Name="MWAT">
      <Column Name="HOBO_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tavg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="movAvg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hoboday" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MWATMax" Member="MWATMaxes">
    <Type Name="MWATMax">
      <Column Name="YEAR_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HOBO_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SITE_NAME" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="MaxMWAT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DaysExceed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Percent]" Member="Percent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COMMENTS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SiteID" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MWMT" Member="MWMTs">
    <Type Name="MWMT">
      <Column Name="HOBO_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tmax" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="movAvg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="hoboday" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MWMTMax" Member="MWMTMaxes">
    <Type Name="MWMTMax">
      <Column Name="YEAR_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HOBO_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SITE_NAME" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="MaxMWMT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DaysExceed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Percent]" Member="Percent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COMMENTS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SiteID" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.lut_SITE_INFO" Member="SiteInfos">
    <Type Name="SiteInfo">
      <Column Name="OBJECTID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Site_ID" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="SITE_NAME" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Directions" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DataStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DataEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Lat" Type="System.Decimal" DbType="Decimal(12,5)" CanBeNull="true" />
      <Column Name="Lng" Type="System.Decimal" DbType="Decimal(12,5)" CanBeNull="true" />
    </Type>
  </Table>
</Database>