#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Garcia")]
public partial class GarciaDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertHOBO(HOBO instance);
  partial void UpdateHOBO(HOBO instance);
  partial void DeleteHOBO(HOBO instance);
  partial void InsertSiteHobo(SiteHobo instance);
  partial void UpdateSiteHobo(SiteHobo instance);
  partial void DeleteSiteHobo(SiteHobo instance);
  partial void InsertSiteInfo(SiteInfo instance);
  partial void UpdateSiteInfo(SiteInfo instance);
  partial void DeleteSiteInfo(SiteInfo instance);
  partial void InsertUser(User instance);
  partial void UpdateUser(User instance);
  partial void DeleteUser(User instance);
  partial void InsertMembership(Membership instance);
  partial void UpdateMembership(Membership instance);
  partial void DeleteMembership(Membership instance);
  partial void InsertUserRole(UserRole instance);
  partial void UpdateUserRole(UserRole instance);
  partial void DeleteUserRole(UserRole instance);
  partial void InsertRole(Role instance);
  partial void UpdateRole(Role instance);
  partial void DeleteRole(Role instance);
  #endregion
	
	public GarciaDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GarciaConnection"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public GarciaDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public GarciaDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public GarciaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public GarciaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<HOBO> HOBOs
	{
		get
		{
			return this.GetTable<HOBO>();
		}
	}
	
	public System.Data.Linq.Table<SITE_INFO> SITE_INFOs
	{
		get
		{
			return this.GetTable<SITE_INFO>();
		}
	}
	
	public System.Data.Linq.Table<SiteXHoboRow> SiteXHoboRows
	{
		get
		{
			return this.GetTable<SiteXHoboRow>();
		}
	}
	
	public System.Data.Linq.Table<SITE> SITEs
	{
		get
		{
			return this.GetTable<SITE>();
		}
	}
	
	public System.Data.Linq.Table<SiteHobo> SiteHobos
	{
		get
		{
			return this.GetTable<SiteHobo>();
		}
	}
	
	public System.Data.Linq.Table<FinalMWAT> FinalMWATs
	{
		get
		{
			return this.GetTable<FinalMWAT>();
		}
	}
	
	public System.Data.Linq.Table<FinalMWMT> FinalMWMTs
	{
		get
		{
			return this.GetTable<FinalMWMT>();
		}
	}
	
	public System.Data.Linq.Table<MWAT> MWATs
	{
		get
		{
			return this.GetTable<MWAT>();
		}
	}
	
	public System.Data.Linq.Table<MWATMax> MWATMaxes
	{
		get
		{
			return this.GetTable<MWATMax>();
		}
	}
	
	public System.Data.Linq.Table<MWMT> MWMTs
	{
		get
		{
			return this.GetTable<MWMT>();
		}
	}
	
	public System.Data.Linq.Table<MWMTMax> MWMTMaxes
	{
		get
		{
			return this.GetTable<MWMTMax>();
		}
	}
	
	public System.Data.Linq.Table<SiteInfo> SiteInfos
	{
		get
		{
			return this.GetTable<SiteInfo>();
		}
	}
	
	public System.Data.Linq.Table<User> Users
	{
		get
		{
			return this.GetTable<User>();
		}
	}
	
	public System.Data.Linq.Table<Membership> Memberships
	{
		get
		{
			return this.GetTable<Membership>();
		}
	}
	
	public System.Data.Linq.Table<UserRole> UserRoles
	{
		get
		{
			return this.GetTable<UserRole>();
		}
	}
	
	public System.Data.Linq.Table<Role> Roles
	{
		get
		{
			return this.GetTable<Role>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOBO")]
public partial class HOBO : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _HOBO_ID;
	
	private System.Nullable<System.DateTime> @__DateTime;
	
	private System.Nullable<double> _Temp;
	
	private System.Nullable<double> _DewPoint;
	
	private System.Nullable<double> _AbsHumidity;
	
	private System.Nullable<double> _RH;
	
	private System.Nullable<System.DateTime> _DateUploaded;
	
	private string _UploadedBy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHOBO_IDChanging(string value);
    partial void OnHOBO_IDChanged();
    partial void On_DateTimeChanging(System.Nullable<System.DateTime> value);
    partial void On_DateTimeChanged();
    partial void OnTempChanging(System.Nullable<double> value);
    partial void OnTempChanged();
    partial void OnDewPointChanging(System.Nullable<double> value);
    partial void OnDewPointChanged();
    partial void OnAbsHumidityChanging(System.Nullable<double> value);
    partial void OnAbsHumidityChanged();
    partial void OnRHChanging(System.Nullable<double> value);
    partial void OnRHChanged();
    partial void OnDateUploadedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateUploadedChanged();
    partial void OnUploadedByChanging(string value);
    partial void OnUploadedByChanged();
    #endregion
	
	public HOBO()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBO_ID", DbType="VarChar(50)")]
	public string HOBO_ID
	{
		get
		{
			return this._HOBO_ID;
		}
		set
		{
			if ((this._HOBO_ID != value))
			{
				this.OnHOBO_IDChanging(value);
				this.SendPropertyChanging();
				this._HOBO_ID = value;
				this.SendPropertyChanged("HOBO_ID");
				this.OnHOBO_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_DateTime]", Storage="__DateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> _DateTime
	{
		get
		{
			return this.@__DateTime;
		}
		set
		{
			if ((this.@__DateTime != value))
			{
				this.On_DateTimeChanging(value);
				this.SendPropertyChanging();
				this.@__DateTime = value;
				this.SendPropertyChanged("_DateTime");
				this.On_DateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temp", DbType="Float")]
	public System.Nullable<double> Temp
	{
		get
		{
			return this._Temp;
		}
		set
		{
			if ((this._Temp != value))
			{
				this.OnTempChanging(value);
				this.SendPropertyChanging();
				this._Temp = value;
				this.SendPropertyChanged("Temp");
				this.OnTempChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DewPoint", DbType="Float")]
	public System.Nullable<double> DewPoint
	{
		get
		{
			return this._DewPoint;
		}
		set
		{
			if ((this._DewPoint != value))
			{
				this.OnDewPointChanging(value);
				this.SendPropertyChanging();
				this._DewPoint = value;
				this.SendPropertyChanged("DewPoint");
				this.OnDewPointChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbsHumidity", DbType="Float")]
	public System.Nullable<double> AbsHumidity
	{
		get
		{
			return this._AbsHumidity;
		}
		set
		{
			if ((this._AbsHumidity != value))
			{
				this.OnAbsHumidityChanging(value);
				this.SendPropertyChanging();
				this._AbsHumidity = value;
				this.SendPropertyChanged("AbsHumidity");
				this.OnAbsHumidityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RH", DbType="Float")]
	public System.Nullable<double> RH
	{
		get
		{
			return this._RH;
		}
		set
		{
			if ((this._RH != value))
			{
				this.OnRHChanging(value);
				this.SendPropertyChanging();
				this._RH = value;
				this.SendPropertyChanged("RH");
				this.OnRHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUploaded", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateUploaded
	{
		get
		{
			return this._DateUploaded;
		}
		set
		{
			if ((this._DateUploaded != value))
			{
				this.OnDateUploadedChanging(value);
				this.SendPropertyChanging();
				this._DateUploaded = value;
				this.SendPropertyChanged("DateUploaded");
				this.OnDateUploadedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedBy", DbType="VarChar(50)")]
	public string UploadedBy
	{
		get
		{
			return this._UploadedBy;
		}
		set
		{
			if ((this._UploadedBy != value))
			{
				this.OnUploadedByChanging(value);
				this.SendPropertyChanging();
				this._UploadedBy = value;
				this.SendPropertyChanged("UploadedBy");
				this.OnUploadedByChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lut_SITE_INFO")]
public partial class SITE_INFO
{
	
	private int _OBJECTID;
	
	private string _Site_ID;
	
	private string _SITE_NAME;
	
	private string _Directions;
	
	public SITE_INFO()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int OBJECTID
	{
		get
		{
			return this._OBJECTID;
		}
		set
		{
			if ((this._OBJECTID != value))
			{
				this._OBJECTID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_ID", DbType="NVarChar(12)")]
	public string Site_ID
	{
		get
		{
			return this._Site_ID;
		}
		set
		{
			if ((this._Site_ID != value))
			{
				this._Site_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_NAME", DbType="NVarChar(150)")]
	public string SITE_NAME
	{
		get
		{
			return this._SITE_NAME;
		}
		set
		{
			if ((this._SITE_NAME != value))
			{
				this._SITE_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Directions", DbType="NVarChar(MAX)")]
	public string Directions
	{
		get
		{
			return this._Directions;
		}
		set
		{
			if ((this._Directions != value))
			{
				this._Directions = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lut_SITE_x_HOBO")]
public partial class SiteXHoboRow
{
	
	private int _OBJECTID;
	
	private string _SITE_ID;
	
	private string _HOBO_ID;
	
	private string _YEAR_;
	
	private string _TYPE;
	
	private string _CONTRIBUTOR;
	
	private string _COMMENTS;
	
	public SiteXHoboRow()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int OBJECTID
	{
		get
		{
			return this._OBJECTID;
		}
		set
		{
			if ((this._OBJECTID != value))
			{
				this._OBJECTID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_ID", DbType="NVarChar(20)")]
	public string SITE_ID
	{
		get
		{
			return this._SITE_ID;
		}
		set
		{
			if ((this._SITE_ID != value))
			{
				this._SITE_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBO_ID", DbType="NVarChar(50)")]
	public string HOBO_ID
	{
		get
		{
			return this._HOBO_ID;
		}
		set
		{
			if ((this._HOBO_ID != value))
			{
				this._HOBO_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_", DbType="NVarChar(50)")]
	public string YEAR_
	{
		get
		{
			return this._YEAR_;
		}
		set
		{
			if ((this._YEAR_ != value))
			{
				this._YEAR_ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(25)")]
	public string TYPE
	{
		get
		{
			return this._TYPE;
		}
		set
		{
			if ((this._TYPE != value))
			{
				this._TYPE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRIBUTOR", DbType="NVarChar(50)")]
	public string CONTRIBUTOR
	{
		get
		{
			return this._CONTRIBUTOR;
		}
		set
		{
			if ((this._CONTRIBUTOR != value))
			{
				this._CONTRIBUTOR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENTS", DbType="NVarChar(255)")]
	public string COMMENTS
	{
		get
		{
			return this._COMMENTS;
		}
		set
		{
			if ((this._COMMENTS != value))
			{
				this._COMMENTS = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="sdeloader.SITE")]
public partial class SITE
{
	
	private int _OBJECTID;
	
	private string _Site_ID;
	
	private System.Nullable<int> _Shape;
	
	public SITE()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int OBJECTID
	{
		get
		{
			return this._OBJECTID;
		}
		set
		{
			if ((this._OBJECTID != value))
			{
				this._OBJECTID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_ID", DbType="NVarChar(12)")]
	public string Site_ID
	{
		get
		{
			return this._Site_ID;
		}
		set
		{
			if ((this._Site_ID != value))
			{
				this._Site_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shape", DbType="Int")]
	public System.Nullable<int> Shape
	{
		get
		{
			return this._Shape;
		}
		set
		{
			if ((this._Shape != value))
			{
				this._Shape = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lut_SITE_x_HOBO")]
public partial class SiteHobo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _OBJECTID;
	
	private string _SITE_ID;
	
	private string _HOBO_ID;
	
	private string _YEAR_;
	
	private string _TYPE;
	
	private string _CONTRIBUTOR;
	
	private string _COMMENTS;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTIDChanging(int value);
    partial void OnOBJECTIDChanged();
    partial void OnSITE_IDChanging(string value);
    partial void OnSITE_IDChanged();
    partial void OnHOBO_IDChanging(string value);
    partial void OnHOBO_IDChanged();
    partial void OnYEAR_Changing(string value);
    partial void OnYEAR_Changed();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnCONTRIBUTORChanging(string value);
    partial void OnCONTRIBUTORChanged();
    partial void OnCOMMENTSChanging(string value);
    partial void OnCOMMENTSChanged();
    #endregion
	
	public SiteHobo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int OBJECTID
	{
		get
		{
			return this._OBJECTID;
		}
		set
		{
			if ((this._OBJECTID != value))
			{
				this.OnOBJECTIDChanging(value);
				this.SendPropertyChanging();
				this._OBJECTID = value;
				this.SendPropertyChanged("OBJECTID");
				this.OnOBJECTIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_ID", DbType="NVarChar(20)")]
	public string SITE_ID
	{
		get
		{
			return this._SITE_ID;
		}
		set
		{
			if ((this._SITE_ID != value))
			{
				this.OnSITE_IDChanging(value);
				this.SendPropertyChanging();
				this._SITE_ID = value;
				this.SendPropertyChanged("SITE_ID");
				this.OnSITE_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBO_ID", DbType="NVarChar(50)")]
	public string HOBO_ID
	{
		get
		{
			return this._HOBO_ID;
		}
		set
		{
			if ((this._HOBO_ID != value))
			{
				this.OnHOBO_IDChanging(value);
				this.SendPropertyChanging();
				this._HOBO_ID = value;
				this.SendPropertyChanged("HOBO_ID");
				this.OnHOBO_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_", DbType="NVarChar(50)")]
	public string YEAR_
	{
		get
		{
			return this._YEAR_;
		}
		set
		{
			if ((this._YEAR_ != value))
			{
				this.OnYEAR_Changing(value);
				this.SendPropertyChanging();
				this._YEAR_ = value;
				this.SendPropertyChanged("YEAR_");
				this.OnYEAR_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(25)")]
	public string TYPE
	{
		get
		{
			return this._TYPE;
		}
		set
		{
			if ((this._TYPE != value))
			{
				this.OnTYPEChanging(value);
				this.SendPropertyChanging();
				this._TYPE = value;
				this.SendPropertyChanged("TYPE");
				this.OnTYPEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRIBUTOR", DbType="NVarChar(50)")]
	public string CONTRIBUTOR
	{
		get
		{
			return this._CONTRIBUTOR;
		}
		set
		{
			if ((this._CONTRIBUTOR != value))
			{
				this.OnCONTRIBUTORChanging(value);
				this.SendPropertyChanging();
				this._CONTRIBUTOR = value;
				this.SendPropertyChanged("CONTRIBUTOR");
				this.OnCONTRIBUTORChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENTS", DbType="NVarChar(255)")]
	public string COMMENTS
	{
		get
		{
			return this._COMMENTS;
		}
		set
		{
			if ((this._COMMENTS != value))
			{
				this.OnCOMMENTSChanging(value);
				this.SendPropertyChanging();
				this._COMMENTS = value;
				this.SendPropertyChanged("COMMENTS");
				this.OnCOMMENTSChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FinalMWAT")]
public partial class FinalMWAT
{
	
	private string _SITE_NAME;
	
	private string _TYPE;
	
	private string _HOBO_ID;
	
	private System.Nullable<System.DateTime> _Date;
	
	private System.Nullable<double> _tavg;
	
	private System.Nullable<double> _movAvg;
	
	private string _hoboday;
	
	private System.Nullable<decimal> _threshold;
	
	private string _YEAR_;
	
	private System.Nullable<double> _MaxOfmovAvg;
	
	private string _SiteID;
	
	public FinalMWAT()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_NAME", DbType="NVarChar(150)")]
	public string SITE_NAME
	{
		get
		{
			return this._SITE_NAME;
		}
		set
		{
			if ((this._SITE_NAME != value))
			{
				this._SITE_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(25)")]
	public string TYPE
	{
		get
		{
			return this._TYPE;
		}
		set
		{
			if ((this._TYPE != value))
			{
				this._TYPE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBO_ID", DbType="NVarChar(50)")]
	public string HOBO_ID
	{
		get
		{
			return this._HOBO_ID;
		}
		set
		{
			if ((this._HOBO_ID != value))
			{
				this._HOBO_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this._Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tavg", DbType="Float")]
	public System.Nullable<double> tavg
	{
		get
		{
			return this._tavg;
		}
		set
		{
			if ((this._tavg != value))
			{
				this._tavg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_movAvg", DbType="Float")]
	public System.Nullable<double> movAvg
	{
		get
		{
			return this._movAvg;
		}
		set
		{
			if ((this._movAvg != value))
			{
				this._movAvg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoboday", DbType="NVarChar(255)")]
	public string hoboday
	{
		get
		{
			return this._hoboday;
		}
		set
		{
			if ((this._hoboday != value))
			{
				this._hoboday = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_threshold", DbType="Decimal(28,1)")]
	public System.Nullable<decimal> threshold
	{
		get
		{
			return this._threshold;
		}
		set
		{
			if ((this._threshold != value))
			{
				this._threshold = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_", DbType="NVarChar(50)")]
	public string YEAR_
	{
		get
		{
			return this._YEAR_;
		}
		set
		{
			if ((this._YEAR_ != value))
			{
				this._YEAR_ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxOfmovAvg", DbType="Float")]
	public System.Nullable<double> MaxOfmovAvg
	{
		get
		{
			return this._MaxOfmovAvg;
		}
		set
		{
			if ((this._MaxOfmovAvg != value))
			{
				this._MaxOfmovAvg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="NVarChar(12)")]
	public string SiteID
	{
		get
		{
			return this._SiteID;
		}
		set
		{
			if ((this._SiteID != value))
			{
				this._SiteID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FinalMWMT")]
public partial class FinalMWMT
{
	
	private string _SiteID;
	
	private string _SITE_NAME;
	
	private string _TYPE;
	
	private string _HOBO_ID;
	
	private System.Nullable<System.DateTime> _Date;
	
	private System.Nullable<double> _tmax;
	
	private System.Nullable<double> _movAvg;
	
	private string _hoboday;
	
	private System.Nullable<decimal> _threshold;
	
	private string _YEAR_;
	
	private System.Nullable<double> _MaxOfmovAvg;
	
	public FinalMWMT()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="NVarChar(12)")]
	public string SiteID
	{
		get
		{
			return this._SiteID;
		}
		set
		{
			if ((this._SiteID != value))
			{
				this._SiteID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_NAME", DbType="NVarChar(150)")]
	public string SITE_NAME
	{
		get
		{
			return this._SITE_NAME;
		}
		set
		{
			if ((this._SITE_NAME != value))
			{
				this._SITE_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(25)")]
	public string TYPE
	{
		get
		{
			return this._TYPE;
		}
		set
		{
			if ((this._TYPE != value))
			{
				this._TYPE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBO_ID", DbType="NVarChar(50)")]
	public string HOBO_ID
	{
		get
		{
			return this._HOBO_ID;
		}
		set
		{
			if ((this._HOBO_ID != value))
			{
				this._HOBO_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this._Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tmax", DbType="Float")]
	public System.Nullable<double> tmax
	{
		get
		{
			return this._tmax;
		}
		set
		{
			if ((this._tmax != value))
			{
				this._tmax = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_movAvg", DbType="Float")]
	public System.Nullable<double> movAvg
	{
		get
		{
			return this._movAvg;
		}
		set
		{
			if ((this._movAvg != value))
			{
				this._movAvg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoboday", DbType="NVarChar(255)")]
	public string hoboday
	{
		get
		{
			return this._hoboday;
		}
		set
		{
			if ((this._hoboday != value))
			{
				this._hoboday = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_threshold", DbType="Decimal(28,1)")]
	public System.Nullable<decimal> threshold
	{
		get
		{
			return this._threshold;
		}
		set
		{
			if ((this._threshold != value))
			{
				this._threshold = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_", DbType="NVarChar(50)")]
	public string YEAR_
	{
		get
		{
			return this._YEAR_;
		}
		set
		{
			if ((this._YEAR_ != value))
			{
				this._YEAR_ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxOfmovAvg", DbType="Float")]
	public System.Nullable<double> MaxOfmovAvg
	{
		get
		{
			return this._MaxOfmovAvg;
		}
		set
		{
			if ((this._MaxOfmovAvg != value))
			{
				this._MaxOfmovAvg = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MWAT")]
public partial class MWAT
{
	
	private string _HOBO_ID;
	
	private System.Nullable<System.DateTime> _Date;
	
	private System.Nullable<double> _tavg;
	
	private System.Nullable<double> _movAvg;
	
	private string _hoboday;
	
	public MWAT()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBO_ID", DbType="NVarChar(50)")]
	public string HOBO_ID
	{
		get
		{
			return this._HOBO_ID;
		}
		set
		{
			if ((this._HOBO_ID != value))
			{
				this._HOBO_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this._Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tavg", DbType="Float")]
	public System.Nullable<double> tavg
	{
		get
		{
			return this._tavg;
		}
		set
		{
			if ((this._tavg != value))
			{
				this._tavg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_movAvg", DbType="Float")]
	public System.Nullable<double> movAvg
	{
		get
		{
			return this._movAvg;
		}
		set
		{
			if ((this._movAvg != value))
			{
				this._movAvg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoboday", DbType="NVarChar(255)")]
	public string hoboday
	{
		get
		{
			return this._hoboday;
		}
		set
		{
			if ((this._hoboday != value))
			{
				this._hoboday = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MWATMax")]
public partial class MWATMax
{
	
	private string _YEAR_;
	
	private string _HOBO_ID;
	
	private string _SITE_NAME;
	
	private string _TYPE;
	
	private string _MaxMWAT;
	
	private System.Nullable<int> _DaysExceed;
	
	private System.Nullable<double> _Percent;
	
	private string _COMMENTS;
	
	private string _SiteID;
	
	public MWATMax()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_", DbType="NVarChar(50)")]
	public string YEAR_
	{
		get
		{
			return this._YEAR_;
		}
		set
		{
			if ((this._YEAR_ != value))
			{
				this._YEAR_ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBO_ID", DbType="NVarChar(50)")]
	public string HOBO_ID
	{
		get
		{
			return this._HOBO_ID;
		}
		set
		{
			if ((this._HOBO_ID != value))
			{
				this._HOBO_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_NAME", DbType="NVarChar(150)")]
	public string SITE_NAME
	{
		get
		{
			return this._SITE_NAME;
		}
		set
		{
			if ((this._SITE_NAME != value))
			{
				this._SITE_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(25)")]
	public string TYPE
	{
		get
		{
			return this._TYPE;
		}
		set
		{
			if ((this._TYPE != value))
			{
				this._TYPE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxMWAT", DbType="NVarChar(255)")]
	public string MaxMWAT
	{
		get
		{
			return this._MaxMWAT;
		}
		set
		{
			if ((this._MaxMWAT != value))
			{
				this._MaxMWAT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaysExceed", DbType="Int")]
	public System.Nullable<int> DaysExceed
	{
		get
		{
			return this._DaysExceed;
		}
		set
		{
			if ((this._DaysExceed != value))
			{
				this._DaysExceed = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Percent]", Storage="_Percent", DbType="Float")]
	public System.Nullable<double> Percent
	{
		get
		{
			return this._Percent;
		}
		set
		{
			if ((this._Percent != value))
			{
				this._Percent = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENTS", DbType="NVarChar(255)")]
	public string COMMENTS
	{
		get
		{
			return this._COMMENTS;
		}
		set
		{
			if ((this._COMMENTS != value))
			{
				this._COMMENTS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="NVarChar(12)")]
	public string SiteID
	{
		get
		{
			return this._SiteID;
		}
		set
		{
			if ((this._SiteID != value))
			{
				this._SiteID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MWMT")]
public partial class MWMT
{
	
	private string _HOBO_ID;
	
	private System.Nullable<System.DateTime> _Date;
	
	private System.Nullable<double> _tmax;
	
	private System.Nullable<double> _movAvg;
	
	private string _hoboday;
	
	public MWMT()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBO_ID", DbType="NVarChar(50)")]
	public string HOBO_ID
	{
		get
		{
			return this._HOBO_ID;
		}
		set
		{
			if ((this._HOBO_ID != value))
			{
				this._HOBO_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this._Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tmax", DbType="Float")]
	public System.Nullable<double> tmax
	{
		get
		{
			return this._tmax;
		}
		set
		{
			if ((this._tmax != value))
			{
				this._tmax = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_movAvg", DbType="Float")]
	public System.Nullable<double> movAvg
	{
		get
		{
			return this._movAvg;
		}
		set
		{
			if ((this._movAvg != value))
			{
				this._movAvg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoboday", DbType="NVarChar(255)")]
	public string hoboday
	{
		get
		{
			return this._hoboday;
		}
		set
		{
			if ((this._hoboday != value))
			{
				this._hoboday = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MWMTMax")]
public partial class MWMTMax
{
	
	private string _YEAR_;
	
	private string _HOBO_ID;
	
	private string _SITE_NAME;
	
	private string _TYPE;
	
	private string _MaxMWMT;
	
	private System.Nullable<int> _DaysExceed;
	
	private System.Nullable<double> _Percent;
	
	private string _COMMENTS;
	
	private string _SiteID;
	
	public MWMTMax()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_", DbType="NVarChar(50)")]
	public string YEAR_
	{
		get
		{
			return this._YEAR_;
		}
		set
		{
			if ((this._YEAR_ != value))
			{
				this._YEAR_ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBO_ID", DbType="NVarChar(50)")]
	public string HOBO_ID
	{
		get
		{
			return this._HOBO_ID;
		}
		set
		{
			if ((this._HOBO_ID != value))
			{
				this._HOBO_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_NAME", DbType="NVarChar(150)")]
	public string SITE_NAME
	{
		get
		{
			return this._SITE_NAME;
		}
		set
		{
			if ((this._SITE_NAME != value))
			{
				this._SITE_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(25)")]
	public string TYPE
	{
		get
		{
			return this._TYPE;
		}
		set
		{
			if ((this._TYPE != value))
			{
				this._TYPE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxMWMT", DbType="NVarChar(255)")]
	public string MaxMWMT
	{
		get
		{
			return this._MaxMWMT;
		}
		set
		{
			if ((this._MaxMWMT != value))
			{
				this._MaxMWMT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaysExceed", DbType="Int")]
	public System.Nullable<int> DaysExceed
	{
		get
		{
			return this._DaysExceed;
		}
		set
		{
			if ((this._DaysExceed != value))
			{
				this._DaysExceed = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Percent]", Storage="_Percent", DbType="Float")]
	public System.Nullable<double> Percent
	{
		get
		{
			return this._Percent;
		}
		set
		{
			if ((this._Percent != value))
			{
				this._Percent = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENTS", DbType="NVarChar(255)")]
	public string COMMENTS
	{
		get
		{
			return this._COMMENTS;
		}
		set
		{
			if ((this._COMMENTS != value))
			{
				this._COMMENTS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="NVarChar(12)")]
	public string SiteID
	{
		get
		{
			return this._SiteID;
		}
		set
		{
			if ((this._SiteID != value))
			{
				this._SiteID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lut_SITE_INFO")]
public partial class SiteInfo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _OBJECTID;
	
	private string _Site_ID;
	
	private string _SITE_NAME;
	
	private string _Directions;
	
	private string _Color;
	
	private System.Nullable<System.DateTime> _DataStartDate;
	
	private System.Nullable<System.DateTime> _DataEndDate;
	
	private System.Nullable<decimal> _Lat;
	
	private System.Nullable<decimal> _Lng;
	
	private bool _HideSite;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTIDChanging(int value);
    partial void OnOBJECTIDChanged();
    partial void OnSite_IDChanging(string value);
    partial void OnSite_IDChanged();
    partial void OnSITE_NAMEChanging(string value);
    partial void OnSITE_NAMEChanged();
    partial void OnDirectionsChanging(string value);
    partial void OnDirectionsChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnDataStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDataStartDateChanged();
    partial void OnDataEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDataEndDateChanged();
    partial void OnLatChanging(System.Nullable<decimal> value);
    partial void OnLatChanged();
    partial void OnLngChanging(System.Nullable<decimal> value);
    partial void OnLngChanged();
    partial void OnHideSiteChanging(bool value);
    partial void OnHideSiteChanged();
    #endregion
	
	public SiteInfo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int OBJECTID
	{
		get
		{
			return this._OBJECTID;
		}
		set
		{
			if ((this._OBJECTID != value))
			{
				this.OnOBJECTIDChanging(value);
				this.SendPropertyChanging();
				this._OBJECTID = value;
				this.SendPropertyChanged("OBJECTID");
				this.OnOBJECTIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_ID", DbType="NVarChar(12)")]
	public string Site_ID
	{
		get
		{
			return this._Site_ID;
		}
		set
		{
			if ((this._Site_ID != value))
			{
				this.OnSite_IDChanging(value);
				this.SendPropertyChanging();
				this._Site_ID = value;
				this.SendPropertyChanged("Site_ID");
				this.OnSite_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_NAME", DbType="NVarChar(150)")]
	public string SITE_NAME
	{
		get
		{
			return this._SITE_NAME;
		}
		set
		{
			if ((this._SITE_NAME != value))
			{
				this.OnSITE_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SITE_NAME = value;
				this.SendPropertyChanged("SITE_NAME");
				this.OnSITE_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Directions", DbType="NVarChar(MAX)")]
	public string Directions
	{
		get
		{
			return this._Directions;
		}
		set
		{
			if ((this._Directions != value))
			{
				this.OnDirectionsChanging(value);
				this.SendPropertyChanging();
				this._Directions = value;
				this.SendPropertyChanged("Directions");
				this.OnDirectionsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(15)")]
	public string Color
	{
		get
		{
			return this._Color;
		}
		set
		{
			if ((this._Color != value))
			{
				this.OnColorChanging(value);
				this.SendPropertyChanging();
				this._Color = value;
				this.SendPropertyChanged("Color");
				this.OnColorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataStartDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> DataStartDate
	{
		get
		{
			return this._DataStartDate;
		}
		set
		{
			if ((this._DataStartDate != value))
			{
				this.OnDataStartDateChanging(value);
				this.SendPropertyChanging();
				this._DataStartDate = value;
				this.SendPropertyChanged("DataStartDate");
				this.OnDataStartDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataEndDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> DataEndDate
	{
		get
		{
			return this._DataEndDate;
		}
		set
		{
			if ((this._DataEndDate != value))
			{
				this.OnDataEndDateChanging(value);
				this.SendPropertyChanging();
				this._DataEndDate = value;
				this.SendPropertyChanged("DataEndDate");
				this.OnDataEndDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Decimal(12,5)")]
	public System.Nullable<decimal> Lat
	{
		get
		{
			return this._Lat;
		}
		set
		{
			if ((this._Lat != value))
			{
				this.OnLatChanging(value);
				this.SendPropertyChanging();
				this._Lat = value;
				this.SendPropertyChanged("Lat");
				this.OnLatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lng", DbType="Decimal(12,5)")]
	public System.Nullable<decimal> Lng
	{
		get
		{
			return this._Lng;
		}
		set
		{
			if ((this._Lng != value))
			{
				this.OnLngChanging(value);
				this.SendPropertyChanging();
				this._Lng = value;
				this.SendPropertyChanged("Lng");
				this.OnLngChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HideSite", DbType="Bit NOT NULL")]
	public bool HideSite
	{
		get
		{
			return this._HideSite;
		}
		set
		{
			if ((this._HideSite != value))
			{
				this.OnHideSiteChanging(value);
				this.SendPropertyChanging();
				this._HideSite = value;
				this.SendPropertyChanged("HideSite");
				this.OnHideSiteChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Users")]
public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _ApplicationId;
	
	private System.Guid _UserId;
	
	private string _UserName;
	
	private string _LoweredUserName;
	
	private string _MobileAlias;
	
	private bool _IsAnonymous;
	
	private System.DateTime _LastActivityDate;
	
	private EntityRef<Membership> _Membership;
	
	private EntitySet<UserRole> _UserRoles;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnLoweredUserNameChanging(string value);
    partial void OnLoweredUserNameChanged();
    partial void OnMobileAliasChanging(string value);
    partial void OnMobileAliasChanged();
    partial void OnIsAnonymousChanging(bool value);
    partial void OnIsAnonymousChanged();
    partial void OnLastActivityDateChanging(System.DateTime value);
    partial void OnLastActivityDateChanged();
    #endregion
	
	public User()
	{
		this._Membership = default(EntityRef<Membership>);
		this._UserRoles = new EntitySet<UserRole>(new Action<UserRole>(this.attach_UserRoles), new Action<UserRole>(this.detach_UserRoles));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid ApplicationId
	{
		get
		{
			return this._ApplicationId;
		}
		set
		{
			if ((this._ApplicationId != value))
			{
				this.OnApplicationIdChanging(value);
				this.SendPropertyChanging();
				this._ApplicationId = value;
				this.SendPropertyChanged("ApplicationId");
				this.OnApplicationIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredUserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string LoweredUserName
	{
		get
		{
			return this._LoweredUserName;
		}
		set
		{
			if ((this._LoweredUserName != value))
			{
				this.OnLoweredUserNameChanging(value);
				this.SendPropertyChanging();
				this._LoweredUserName = value;
				this.SendPropertyChanged("LoweredUserName");
				this.OnLoweredUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileAlias", DbType="NVarChar(16)")]
	public string MobileAlias
	{
		get
		{
			return this._MobileAlias;
		}
		set
		{
			if ((this._MobileAlias != value))
			{
				this.OnMobileAliasChanging(value);
				this.SendPropertyChanging();
				this._MobileAlias = value;
				this.SendPropertyChanged("MobileAlias");
				this.OnMobileAliasChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnonymous", DbType="Bit NOT NULL")]
	public bool IsAnonymous
	{
		get
		{
			return this._IsAnonymous;
		}
		set
		{
			if ((this._IsAnonymous != value))
			{
				this.OnIsAnonymousChanging(value);
				this.SendPropertyChanging();
				this._IsAnonymous = value;
				this.SendPropertyChanged("IsAnonymous");
				this.OnIsAnonymousChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityDate", DbType="DateTime NOT NULL")]
	public System.DateTime LastActivityDate
	{
		get
		{
			return this._LastActivityDate;
		}
		set
		{
			if ((this._LastActivityDate != value))
			{
				this.OnLastActivityDateChanging(value);
				this.SendPropertyChanging();
				this._LastActivityDate = value;
				this.SendPropertyChanged("LastActivityDate");
				this.OnLastActivityDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_aspnet_Membership", Storage="_Membership", ThisKey="UserId", OtherKey="UserId", IsUnique=true, IsForeignKey=false)]
	public Membership Membership
	{
		get
		{
			return this._Membership.Entity;
		}
		set
		{
			Membership previousValue = this._Membership.Entity;
			if (((previousValue != value) 
						|| (this._Membership.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Membership.Entity = null;
					previousValue.User = null;
				}
				this._Membership.Entity = value;
				if ((value != null))
				{
					value.User = this;
				}
				this.SendPropertyChanged("Membership");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_aspnet_UsersInRole", Storage="_UserRoles", ThisKey="UserId", OtherKey="UserId")]
	public EntitySet<UserRole> UserRoles
	{
		get
		{
			return this._UserRoles;
		}
		set
		{
			this._UserRoles.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_UserRoles(UserRole entity)
	{
		this.SendPropertyChanging();
		entity.User = this;
	}
	
	private void detach_UserRoles(UserRole entity)
	{
		this.SendPropertyChanging();
		entity.User = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Membership")]
public partial class Membership : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _ApplicationId;
	
	private System.Guid _UserId;
	
	private string _Password;
	
	private int _PasswordFormat;
	
	private string _PasswordSalt;
	
	private string _MobilePIN;
	
	private string _Email;
	
	private string _LoweredEmail;
	
	private string _PasswordQuestion;
	
	private string _PasswordAnswer;
	
	private bool _IsApproved;
	
	private bool _IsLockedOut;
	
	private System.DateTime _CreateDate;
	
	private System.DateTime _LastLoginDate;
	
	private System.DateTime _LastPasswordChangedDate;
	
	private System.DateTime _LastLockoutDate;
	
	private int _FailedPasswordAttemptCount;
	
	private System.DateTime _FailedPasswordAttemptWindowStart;
	
	private int _FailedPasswordAnswerAttemptCount;
	
	private System.DateTime _FailedPasswordAnswerAttemptWindowStart;
	
	private string _Comment;
	
	private EntityRef<User> _User;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPasswordFormatChanging(int value);
    partial void OnPasswordFormatChanged();
    partial void OnPasswordSaltChanging(string value);
    partial void OnPasswordSaltChanged();
    partial void OnMobilePINChanging(string value);
    partial void OnMobilePINChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLoweredEmailChanging(string value);
    partial void OnLoweredEmailChanged();
    partial void OnPasswordQuestionChanging(string value);
    partial void OnPasswordQuestionChanged();
    partial void OnPasswordAnswerChanging(string value);
    partial void OnPasswordAnswerChanged();
    partial void OnIsApprovedChanging(bool value);
    partial void OnIsApprovedChanged();
    partial void OnIsLockedOutChanging(bool value);
    partial void OnIsLockedOutChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnLastLoginDateChanging(System.DateTime value);
    partial void OnLastLoginDateChanged();
    partial void OnLastPasswordChangedDateChanging(System.DateTime value);
    partial void OnLastPasswordChangedDateChanged();
    partial void OnLastLockoutDateChanging(System.DateTime value);
    partial void OnLastLockoutDateChanged();
    partial void OnFailedPasswordAttemptCountChanging(int value);
    partial void OnFailedPasswordAttemptCountChanged();
    partial void OnFailedPasswordAttemptWindowStartChanging(System.DateTime value);
    partial void OnFailedPasswordAttemptWindowStartChanged();
    partial void OnFailedPasswordAnswerAttemptCountChanging(int value);
    partial void OnFailedPasswordAnswerAttemptCountChanged();
    partial void OnFailedPasswordAnswerAttemptWindowStartChanging(System.DateTime value);
    partial void OnFailedPasswordAnswerAttemptWindowStartChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
	
	public Membership()
	{
		this._User = default(EntityRef<User>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid ApplicationId
	{
		get
		{
			return this._ApplicationId;
		}
		set
		{
			if ((this._ApplicationId != value))
			{
				this.OnApplicationIdChanging(value);
				this.SendPropertyChanging();
				this._ApplicationId = value;
				this.SendPropertyChanged("ApplicationId");
				this.OnApplicationIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				if (this._User.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordFormat", DbType="Int NOT NULL")]
	public int PasswordFormat
	{
		get
		{
			return this._PasswordFormat;
		}
		set
		{
			if ((this._PasswordFormat != value))
			{
				this.OnPasswordFormatChanging(value);
				this.SendPropertyChanging();
				this._PasswordFormat = value;
				this.SendPropertyChanged("PasswordFormat");
				this.OnPasswordFormatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordSalt", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
	public string PasswordSalt
	{
		get
		{
			return this._PasswordSalt;
		}
		set
		{
			if ((this._PasswordSalt != value))
			{
				this.OnPasswordSaltChanging(value);
				this.SendPropertyChanging();
				this._PasswordSalt = value;
				this.SendPropertyChanged("PasswordSalt");
				this.OnPasswordSaltChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobilePIN", DbType="NVarChar(16)")]
	public string MobilePIN
	{
		get
		{
			return this._MobilePIN;
		}
		set
		{
			if ((this._MobilePIN != value))
			{
				this.OnMobilePINChanging(value);
				this.SendPropertyChanging();
				this._MobilePIN = value;
				this.SendPropertyChanged("MobilePIN");
				this.OnMobilePINChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(256)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredEmail", DbType="NVarChar(256)")]
	public string LoweredEmail
	{
		get
		{
			return this._LoweredEmail;
		}
		set
		{
			if ((this._LoweredEmail != value))
			{
				this.OnLoweredEmailChanging(value);
				this.SendPropertyChanging();
				this._LoweredEmail = value;
				this.SendPropertyChanged("LoweredEmail");
				this.OnLoweredEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordQuestion", DbType="NVarChar(256)")]
	public string PasswordQuestion
	{
		get
		{
			return this._PasswordQuestion;
		}
		set
		{
			if ((this._PasswordQuestion != value))
			{
				this.OnPasswordQuestionChanging(value);
				this.SendPropertyChanging();
				this._PasswordQuestion = value;
				this.SendPropertyChanged("PasswordQuestion");
				this.OnPasswordQuestionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordAnswer", DbType="NVarChar(128)")]
	public string PasswordAnswer
	{
		get
		{
			return this._PasswordAnswer;
		}
		set
		{
			if ((this._PasswordAnswer != value))
			{
				this.OnPasswordAnswerChanging(value);
				this.SendPropertyChanging();
				this._PasswordAnswer = value;
				this.SendPropertyChanged("PasswordAnswer");
				this.OnPasswordAnswerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsApproved", DbType="Bit NOT NULL")]
	public bool IsApproved
	{
		get
		{
			return this._IsApproved;
		}
		set
		{
			if ((this._IsApproved != value))
			{
				this.OnIsApprovedChanging(value);
				this.SendPropertyChanging();
				this._IsApproved = value;
				this.SendPropertyChanged("IsApproved");
				this.OnIsApprovedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLockedOut", DbType="Bit NOT NULL")]
	public bool IsLockedOut
	{
		get
		{
			return this._IsLockedOut;
		}
		set
		{
			if ((this._IsLockedOut != value))
			{
				this.OnIsLockedOutChanging(value);
				this.SendPropertyChanging();
				this._IsLockedOut = value;
				this.SendPropertyChanged("IsLockedOut");
				this.OnIsLockedOutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
	public System.DateTime CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginDate", DbType="DateTime NOT NULL")]
	public System.DateTime LastLoginDate
	{
		get
		{
			return this._LastLoginDate;
		}
		set
		{
			if ((this._LastLoginDate != value))
			{
				this.OnLastLoginDateChanging(value);
				this.SendPropertyChanging();
				this._LastLoginDate = value;
				this.SendPropertyChanged("LastLoginDate");
				this.OnLastLoginDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPasswordChangedDate", DbType="DateTime NOT NULL")]
	public System.DateTime LastPasswordChangedDate
	{
		get
		{
			return this._LastPasswordChangedDate;
		}
		set
		{
			if ((this._LastPasswordChangedDate != value))
			{
				this.OnLastPasswordChangedDateChanging(value);
				this.SendPropertyChanging();
				this._LastPasswordChangedDate = value;
				this.SendPropertyChanged("LastPasswordChangedDate");
				this.OnLastPasswordChangedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLockoutDate", DbType="DateTime NOT NULL")]
	public System.DateTime LastLockoutDate
	{
		get
		{
			return this._LastLockoutDate;
		}
		set
		{
			if ((this._LastLockoutDate != value))
			{
				this.OnLastLockoutDateChanging(value);
				this.SendPropertyChanging();
				this._LastLockoutDate = value;
				this.SendPropertyChanged("LastLockoutDate");
				this.OnLastLockoutDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAttemptCount", DbType="Int NOT NULL")]
	public int FailedPasswordAttemptCount
	{
		get
		{
			return this._FailedPasswordAttemptCount;
		}
		set
		{
			if ((this._FailedPasswordAttemptCount != value))
			{
				this.OnFailedPasswordAttemptCountChanging(value);
				this.SendPropertyChanging();
				this._FailedPasswordAttemptCount = value;
				this.SendPropertyChanged("FailedPasswordAttemptCount");
				this.OnFailedPasswordAttemptCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAttemptWindowStart", DbType="DateTime NOT NULL")]
	public System.DateTime FailedPasswordAttemptWindowStart
	{
		get
		{
			return this._FailedPasswordAttemptWindowStart;
		}
		set
		{
			if ((this._FailedPasswordAttemptWindowStart != value))
			{
				this.OnFailedPasswordAttemptWindowStartChanging(value);
				this.SendPropertyChanging();
				this._FailedPasswordAttemptWindowStart = value;
				this.SendPropertyChanged("FailedPasswordAttemptWindowStart");
				this.OnFailedPasswordAttemptWindowStartChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAnswerAttemptCount", DbType="Int NOT NULL")]
	public int FailedPasswordAnswerAttemptCount
	{
		get
		{
			return this._FailedPasswordAnswerAttemptCount;
		}
		set
		{
			if ((this._FailedPasswordAnswerAttemptCount != value))
			{
				this.OnFailedPasswordAnswerAttemptCountChanging(value);
				this.SendPropertyChanging();
				this._FailedPasswordAnswerAttemptCount = value;
				this.SendPropertyChanged("FailedPasswordAnswerAttemptCount");
				this.OnFailedPasswordAnswerAttemptCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAnswerAttemptWindowStart", DbType="DateTime NOT NULL")]
	public System.DateTime FailedPasswordAnswerAttemptWindowStart
	{
		get
		{
			return this._FailedPasswordAnswerAttemptWindowStart;
		}
		set
		{
			if ((this._FailedPasswordAnswerAttemptWindowStart != value))
			{
				this.OnFailedPasswordAnswerAttemptWindowStartChanging(value);
				this.SendPropertyChanging();
				this._FailedPasswordAnswerAttemptWindowStart = value;
				this.SendPropertyChanged("FailedPasswordAnswerAttemptWindowStart");
				this.OnFailedPasswordAnswerAttemptWindowStartChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Comment
	{
		get
		{
			return this._Comment;
		}
		set
		{
			if ((this._Comment != value))
			{
				this.OnCommentChanging(value);
				this.SendPropertyChanging();
				this._Comment = value;
				this.SendPropertyChanged("Comment");
				this.OnCommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_aspnet_Membership", Storage="_User", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true)]
	public User User
	{
		get
		{
			return this._User.Entity;
		}
		set
		{
			User previousValue = this._User.Entity;
			if (((previousValue != value) 
						|| (this._User.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._User.Entity = null;
					previousValue.Membership = null;
				}
				this._User.Entity = value;
				if ((value != null))
				{
					value.Membership = this;
					this._UserId = value.UserId;
				}
				else
				{
					this._UserId = default(System.Guid);
				}
				this.SendPropertyChanged("User");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_UsersInRoles")]
public partial class UserRole : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _UserId;
	
	private System.Guid _RoleId;
	
	private EntityRef<User> _User;
	
	private EntityRef<Role> _Role;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnRoleIdChanging(System.Guid value);
    partial void OnRoleIdChanged();
    #endregion
	
	public UserRole()
	{
		this._User = default(EntityRef<User>);
		this._Role = default(EntityRef<Role>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				if (this._User.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid RoleId
	{
		get
		{
			return this._RoleId;
		}
		set
		{
			if ((this._RoleId != value))
			{
				if (this._Role.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnRoleIdChanging(value);
				this.SendPropertyChanging();
				this._RoleId = value;
				this.SendPropertyChanged("RoleId");
				this.OnRoleIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_aspnet_UsersInRole", Storage="_User", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true)]
	public User User
	{
		get
		{
			return this._User.Entity;
		}
		set
		{
			User previousValue = this._User.Entity;
			if (((previousValue != value) 
						|| (this._User.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._User.Entity = null;
					previousValue.UserRoles.Remove(this);
				}
				this._User.Entity = value;
				if ((value != null))
				{
					value.UserRoles.Add(this);
					this._UserId = value.UserId;
				}
				else
				{
					this._UserId = default(System.Guid);
				}
				this.SendPropertyChanged("User");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_Role_UserRole", Storage="_Role", ThisKey="RoleId", OtherKey="RoleId", IsForeignKey=true)]
	public Role Role
	{
		get
		{
			return this._Role.Entity;
		}
		set
		{
			Role previousValue = this._Role.Entity;
			if (((previousValue != value) 
						|| (this._Role.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Role.Entity = null;
					previousValue.UserRoles.Remove(this);
				}
				this._Role.Entity = value;
				if ((value != null))
				{
					value.UserRoles.Add(this);
					this._RoleId = value.RoleId;
				}
				else
				{
					this._RoleId = default(System.Guid);
				}
				this.SendPropertyChanged("Role");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Roles")]
public partial class Role : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _ApplicationId;
	
	private System.Guid _RoleId;
	
	private string _RoleName;
	
	private string _LoweredRoleName;
	
	private string _Description;
	
	private EntitySet<UserRole> _UserRoles;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnRoleIdChanging(System.Guid value);
    partial void OnRoleIdChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    partial void OnLoweredRoleNameChanging(string value);
    partial void OnLoweredRoleNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
	
	public Role()
	{
		this._UserRoles = new EntitySet<UserRole>(new Action<UserRole>(this.attach_UserRoles), new Action<UserRole>(this.detach_UserRoles));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid ApplicationId
	{
		get
		{
			return this._ApplicationId;
		}
		set
		{
			if ((this._ApplicationId != value))
			{
				this.OnApplicationIdChanging(value);
				this.SendPropertyChanging();
				this._ApplicationId = value;
				this.SendPropertyChanged("ApplicationId");
				this.OnApplicationIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid RoleId
	{
		get
		{
			return this._RoleId;
		}
		set
		{
			if ((this._RoleId != value))
			{
				this.OnRoleIdChanging(value);
				this.SendPropertyChanging();
				this._RoleId = value;
				this.SendPropertyChanged("RoleId");
				this.OnRoleIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string RoleName
	{
		get
		{
			return this._RoleName;
		}
		set
		{
			if ((this._RoleName != value))
			{
				this.OnRoleNameChanging(value);
				this.SendPropertyChanging();
				this._RoleName = value;
				this.SendPropertyChanged("RoleName");
				this.OnRoleNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredRoleName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string LoweredRoleName
	{
		get
		{
			return this._LoweredRoleName;
		}
		set
		{
			if ((this._LoweredRoleName != value))
			{
				this.OnLoweredRoleNameChanging(value);
				this.SendPropertyChanging();
				this._LoweredRoleName = value;
				this.SendPropertyChanged("LoweredRoleName");
				this.OnLoweredRoleNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(256)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_Role_UserRole", Storage="_UserRoles", ThisKey="RoleId", OtherKey="RoleId")]
	public EntitySet<UserRole> UserRoles
	{
		get
		{
			return this._UserRoles;
		}
		set
		{
			this._UserRoles.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_UserRoles(UserRole entity)
	{
		this.SendPropertyChanging();
		entity.Role = this;
	}
	
	private void detach_UserRoles(UserRole entity)
	{
		this.SendPropertyChanging();
		entity.Role = null;
	}
}
#pragma warning restore 1591
