//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.SLService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SilverlightServiceCallResult", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class SilverlightServiceCallResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.SLService.ServiceCallResult serviceCallResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.SLService.ServiceCallResult serviceCallResult {
            get {
                return this.serviceCallResultField;
            }
            set {
                if ((this.serviceCallResultField.Equals(value) != true)) {
                    this.serviceCallResultField = value;
                    this.RaisePropertyChanged("serviceCallResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceCallResult", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum ServiceCallResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeeklyTemp", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class WeeklyTemp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double movAvgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateString {
            get {
                return this.dateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.dateStringField, value) != true)) {
                    this.dateStringField = value;
                    this.RaisePropertyChanged("dateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double movAvg {
            get {
                return this.movAvgField;
            }
            set {
                if ((this.movAvgField.Equals(value) != true)) {
                    this.movAvgField = value;
                    this.RaisePropertyChanged("movAvg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string siteID {
            get {
                return this.siteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.siteIDField, value) != true)) {
                    this.siteIDField = value;
                    this.RaisePropertyChanged("siteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string siteName {
            get {
                return this.siteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.siteNameField, value) != true)) {
                    this.siteNameField = value;
                    this.RaisePropertyChanged("siteName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaxTemp", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MaxTemp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int daysExceedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hoboIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double percentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string percentStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                if ((object.ReferenceEquals(this.commentsField, value) != true)) {
                    this.commentsField = value;
                    this.RaisePropertyChanged("comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int daysExceed {
            get {
                return this.daysExceedField;
            }
            set {
                if ((this.daysExceedField.Equals(value) != true)) {
                    this.daysExceedField = value;
                    this.RaisePropertyChanged("daysExceed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hoboID {
            get {
                return this.hoboIDField;
            }
            set {
                if ((object.ReferenceEquals(this.hoboIDField, value) != true)) {
                    this.hoboIDField = value;
                    this.RaisePropertyChanged("hoboID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string max {
            get {
                return this.maxField;
            }
            set {
                if ((object.ReferenceEquals(this.maxField, value) != true)) {
                    this.maxField = value;
                    this.RaisePropertyChanged("max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double percent {
            get {
                return this.percentField;
            }
            set {
                if ((this.percentField.Equals(value) != true)) {
                    this.percentField = value;
                    this.RaisePropertyChanged("percent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string percentString {
            get {
                return this.percentStringField;
            }
            set {
                if ((object.ReferenceEquals(this.percentStringField, value) != true)) {
                    this.percentStringField = value;
                    this.RaisePropertyChanged("percentString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string siteID {
            get {
                return this.siteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.siteIDField, value) != true)) {
                    this.siteIDField = value;
                    this.RaisePropertyChanged("siteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string siteName {
            get {
                return this.siteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.siteNameField, value) != true)) {
                    this.siteNameField = value;
                    this.RaisePropertyChanged("siteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string year {
            get {
                return this.yearField;
            }
            set {
                if ((object.ReferenceEquals(this.yearField, value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GarciaSite", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class GarciaSite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] airYearsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataDateRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] waterYearsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] airYears {
            get {
                return this.airYearsField;
            }
            set {
                if ((object.ReferenceEquals(this.airYearsField, value) != true)) {
                    this.airYearsField = value;
                    this.RaisePropertyChanged("airYears");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string color {
            get {
                return this.colorField;
            }
            set {
                if ((object.ReferenceEquals(this.colorField, value) != true)) {
                    this.colorField = value;
                    this.RaisePropertyChanged("color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dataDateRange {
            get {
                return this.dataDateRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.dataDateRangeField, value) != true)) {
                    this.dataDateRangeField = value;
                    this.RaisePropertyChanged("dataDateRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataEndDate {
            get {
                return this.dataEndDateField;
            }
            set {
                if ((this.dataEndDateField.Equals(value) != true)) {
                    this.dataEndDateField = value;
                    this.RaisePropertyChanged("dataEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataStartDate {
            get {
                return this.dataStartDateField;
            }
            set {
                if ((this.dataStartDateField.Equals(value) != true)) {
                    this.dataStartDateField = value;
                    this.RaisePropertyChanged("dataStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSelected {
            get {
                return this.isSelectedField;
            }
            set {
                if ((this.isSelectedField.Equals(value) != true)) {
                    this.isSelectedField = value;
                    this.RaisePropertyChanged("isSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string siteID {
            get {
                return this.siteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.siteIDField, value) != true)) {
                    this.siteIDField = value;
                    this.RaisePropertyChanged("siteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string siteName {
            get {
                return this.siteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.siteNameField, value) != true)) {
                    this.siteNameField = value;
                    this.RaisePropertyChanged("siteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] waterYears {
            get {
                return this.waterYearsField;
            }
            set {
                if ((object.ReferenceEquals(this.waterYearsField, value) != true)) {
                    this.waterYearsField = value;
                    this.RaisePropertyChanged("waterYears");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="SLService.SLService")]
    public interface SLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SLService/getYears", ReplyAction="urn:SLService/getYearsResponse")]
        string[] getYears(ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SLService/getMWATData", ReplyAction="urn:SLService/getMWATDataResponse")]
        ConsoleApplication1.SLService.WeeklyTemp[] getMWATData(System.DateTime startDate, System.DateTime endDate, string[] sites, ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SLService/getMaxMWATData", ReplyAction="urn:SLService/getMaxMWATDataResponse")]
        ConsoleApplication1.SLService.MaxTemp[] getMaxMWATData(string year, string[] sites, ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SLService/getMWMTData", ReplyAction="urn:SLService/getMWMTDataResponse")]
        ConsoleApplication1.SLService.WeeklyTemp[] getMWMTData(System.DateTime startDate, System.DateTime endDate, string[] sites, ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SLService/getMaxMWMTData", ReplyAction="urn:SLService/getMaxMWMTDataResponse")]
        ConsoleApplication1.SLService.MaxTemp[] getMaxMWMTData(string year, string[] sites, ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SLService/getSites", ReplyAction="urn:SLService/getSitesResponse")]
        ConsoleApplication1.SLService.GarciaSite[] getSites(ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SLServiceChannel : ConsoleApplication1.SLService.SLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.SLService.SLService>, ConsoleApplication1.SLService.SLService {
        
        public SLServiceClient() {
        }
        
        public SLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getYears(ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr) {
            return base.Channel.getYears(ref sr);
        }
        
        public ConsoleApplication1.SLService.WeeklyTemp[] getMWATData(System.DateTime startDate, System.DateTime endDate, string[] sites, ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr) {
            return base.Channel.getMWATData(startDate, endDate, sites, ref sr);
        }
        
        public ConsoleApplication1.SLService.MaxTemp[] getMaxMWATData(string year, string[] sites, ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr) {
            return base.Channel.getMaxMWATData(year, sites, ref sr);
        }
        
        public ConsoleApplication1.SLService.WeeklyTemp[] getMWMTData(System.DateTime startDate, System.DateTime endDate, string[] sites, ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr) {
            return base.Channel.getMWMTData(startDate, endDate, sites, ref sr);
        }
        
        public ConsoleApplication1.SLService.MaxTemp[] getMaxMWMTData(string year, string[] sites, ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr) {
            return base.Channel.getMaxMWMTData(year, sites, ref sr);
        }
        
        public ConsoleApplication1.SLService.GarciaSite[] getSites(ref ConsoleApplication1.SLService.SilverlightServiceCallResult sr) {
            return base.Channel.getSites(ref sr);
        }
    }
}
